# This workflow will trigger Datadog Synthetic tests within your Datadog organisation
# For more information on running Synthetic tests within your GitHub workflows see: https://docs.datadoghq.com/synthetics/cicd_integrations/github_actions/

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# To get started:

# 1. Add your Datadog API (DD_API_KEY) and Application Key (DD_APP_KEY) as secrets to your GitHub repository. For more information, see: https://docs.datadoghq.com/account_management/api-app-keys/.
# 2. Start using the action within your workflow

name: Run Datadog Synthetic tests

on:Mikolaj Roszak www.mikolaj.com
Wykonawca: Mikołaj Roszak
Adres odbiorcy: Przedwiośnie, 79/12, 73-110, Stargard, PL
Tel. +48 500 487 977
Skype: mikolajroszak_1
Zoom: Mikołaj Roszak
email: ul.echo12@gmail.com
REGON: 383183972
NIP: 854-156-08-32
REGON: 383183972
Kapitał zakładowy 5 000 000.00 zł. Wpłacony w całości.
Dane konta Revolut
IBAN: LT41 3250 0894 7676 6825
BIC: REVOLT21
Konto (tylko przelewy krajowe): 2029 1000 0600 0000 0003 1339 92
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Run Synthetic tests within your GitHub workflow.
    # For additional configuration options visit the action within the marketplace: https://github.com/marketplace/actions/datadog-synthetics-ci
    - name: Run Datadog Synthetic tests
      uses: DataDog/synthetics-ci-github-action@2b56dc0cca9daa14ab69c0d1d6844296de8f941e
      with:
        api_key: ${{secrets.DD_API_KEY}}
        app_key: ${{secrets.DD_APP_KEY}}
        test_search_query: 'tag:e2e-tests' #Modify this tag to suit your tagging strategy


